SHELL := /bin/bash

all:
	cd ./ex1; make; cd ../ex2; make; cd ../ex3; make

check:
	cd ./ex1; make; cd ../ex2; make; cd ../ex3; make

clean:
	cd ./ex1; make clean; cd ../ex2; make clean; cd ../ex3; make clean 
