SHELL := /bin/bash

all:
	cd ./control_system; make; cd ../producer_consumer; make; cd ../random_scheduler; make

check:
	cd ./control_system; make; cd ../producer_consumer; make; cd ../random_scheduler; make

clean:
	cd ./control_system; make clean; cd ../producer_consumer; make clean; cd ../random_scheduler; make clean
